<?php if ($stateTerritories): ?>
<table>
    <thead>
    <tr>
        <th scope="col">State/Territory</th>
        <th scope="col">Schedule count</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($stateTerritories as $stateTerritoryName => $stateTerritory): ?>
    <tr>
        <?php if ($stateTerritory['state_territory_representation']): ?>
        <td><?php echo $stateTerritory['state_territory_representation']->link($stateTerritory['state_territory_representation']->displayTitle()); ?></td>
        <?php else: ?>
        <td><?php echo $stateTerritoryName; ?></td>
        <?php endif; ?>
        <td><?php echo $stateTerritory['schedule_count']; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>

<?php if ($counties): ?>
<table>
    <thead>
    <tr>
        <th>County</th>
        <th>Schedule count</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($counties as $county): ?>
    <tr>
        <td><?php echo $county['county_representation']->link($county['county_representation']->displayTitle()); ?></td>
        <td><?php echo $county['schedule_count']; ?></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
